<?php

/*
 * Implementation of hook_block_info().
 */
function servicestatus_block_info() 
{    
    $blocks['mta-service-status'] = array(
            'info' => t('MTA Service Status'),
            'cache' => DRUPAL_NO_CACHE,
     		// 'cache' => DRUPAL_CACHE_GLOBAL,
    );

    return $blocks;
}

function servicestatus_menu()
{
    $item['status/%/%'] = array(
        'title' => "MTA Service Status",
        'access arguments' => array('access content'),
        'page callback' => 'getStatusDetails',
        'page arguments' => array(1,2),
    );

    $item['service_status_json'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'getStatusAsJSON',
        'delivery callback' => 'drupal_json_output',
    );

    return $item;
}

function getStatusDetails($service, $line)
{
    // $output = '<div id="status_display"></div>';
    $output = '<div id="status_display">';
    // drupal_add_js('jQuery(document).ready(function () { jQuery("#status_display").mtaService("'.$service.'", "'.$line.'"); });', 'inline');
    
    $json_str = getStatusAsJSON();
    $json = json_decode($json_str, TRUE);
    // dsm($json);

    $data = null;
    if ($service == "subway")
        $data = $json["subway"]["line"];
    elseif ($service == "LIRR")
        $data = $json["LIRR"]["line"];
    elseif ($service == "MetroNorth")
        $data = $json["MetroNorth"]["line"];
    elseif ($service == "bus")
        $data = $json["bus"]["line"];
    elseif ($service == "BT")
        $data = $json["BT"]["line"];

    $detailed_message = "";
    $bNotFound = TRUE;

    foreach ($data as $index) {
        if ($bNotFound){
            foreach($index as $value) {
                $line_n = $index['name'];

                if ($service != "subway") {
                    $line_n = str_replace(' ', '', $line_n);
                    $line_n = str_replace('.', '', $line_n);
                }

                if ($line_n == $line) {
                    if ($index['text'])
                        $detailed_message = $index['text'];
                    else
                        $detailed_message = "The Service Status has changed. Please go back to the MTA home page for fresh status."; 
                    
                    $bNotFound = false;
                    break;
                }                               
            }
        }
    }
    
    // print_r ($json);
    $output .= $detailed_message . '</div>';

    // $html = html_entity_decode($output);

    // run $html through MTA input filter to translate tokens to images
    $filteredhtml = check_markup($output, 'full_html');

    return $filteredhtml;
}

function getStatusAsJSON()
{
    $fileContents= file_get_contents("http://web.mta.info/status/serviceStatus.txt");
    $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
    $fileContents = trim(str_replace('"', "'", $fileContents));
    $simpleXml = simplexml_load_string($fileContents);
    $json = json_encode($simpleXml);
    
    // drupal_json_output($json);
    return $json;
}

/*
 * Implementation of hook_block_view().
 */
function servicestatus_block_view($delta ='') 
{
    $block = array();

    switch ($delta) 
    {
        case 'mta-service-status':
            $block['title'] = t('Service Status');
            $block['subject'] = t('');

            $block['content'] = '<div id="status-whole-block"></div>';
        break;
    }
    
    return $block;
}