<?php
/*
 * Implementation of hook_block_info().
 */
function servicestatus_block_info() 
{    
    $blocks['mta-service-status'] = array(
            'info' => t('MTA Service Status'),
            'cache' => DRUPAL_NO_CACHE,
     		// 'cache' => DRUPAL_CACHE_GLOBAL,
    );

    return $blocks;
}

function servicestatus_menu()
{
    $item['status/%/%'] = array(
        'title' => "MTA Service Status",
        'access arguments' => array('access content'),
        'page callback' => 'getStatusDetails',
        'page arguments' => array(1,2),
    );

    $item['service_status_json'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'getStatusAsJSON',
        'delivery callback' => 'drupal_json_output',
    );

    return $item;
}

function getStatusDetails($service, $line)
{
    // Verify params
    $output = '<div id="status_display">';
    // drupal_add_js('jQuery(document).ready(function () { jQuery("#status_display").mtaService("'.$service.'", "'.$line.'"); });', 'inline');
    
    $json_str = getStatusAsJSON();
    $json = json_decode($json_str, TRUE);

    $data = null;
    if ($service == "subway")
        $data = $json["subway"]["line"];
    elseif ($service == "LIRR")
        $data = $json["LIRR"]["line"];
    elseif ($service == "MetroNorth")
        $data = $json["MetroNorth"]["line"];
    elseif ($service == "bus")
        $data = $json["bus"]["line"];
    elseif ($service == "BT")
        $data = $json["BT"]["line"];

    $detailed_message = "";
    $bNotFound = TRUE;

    foreach ($data as $index) {
        if ($bNotFound){
            foreach($index as $value) {
                $line_n = $index['name'];

                if ($service != "subway") {
                    $line_n = str_replace(' ', '', $line_n);
                    $line_n = str_replace('.', '', $line_n);
                }

                if ($line_n == $line) {
                    if ($service == "LIRR" || $service == "MetroNorth")
                        $detailed_message = generateRailHeading($line_n);

                    if ($index['text'])
                        $detailed_message .= $index['text'];
                    else
                        $detailed_message .= "The Service Status has changed. Please go back to the MTA home page for latest status."; 
                    
                    $bNotFound = false;
                    break;
                }                               
            }
        }
    }
    
    // dsm ($json);
    $output .= $detailed_message . '</div>';

    // $html = html_entity_decode($output);

    // Run through MTA input filter to translate tokens to images
    $filteredhtml = check_markup($output, 'full_html');

    return $filteredhtml;
}

function getStatusAsJSON()
{
    $fileContents= file_get_contents("http://web.mta.info/status/serviceStatus.txt");
    $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
    $fileContents = trim(str_replace('"', "'", $fileContents));
    $simpleXml = simplexml_load_string($fileContents);
    $json = json_encode($simpleXml);
    
    // drupal_json_output($json);
    return $json;
}

function generateRailHeading($line)
{
    switch ($line) {
        // LIRR
        case "Babylon":
            $linename = "Babylon Branch Customers";
            $color = "#00985F";
            break;
        case "CityTerminalZone":
            $linename = "City Terminal Zone Branch Customers";
            $color = "#4D5357";
            break;
        case "FarRockaway":
            $linename = "Far Rockaway Branch Customers";
            $color = "#6E3219";
            break;                
        case "Hempstead":
            $linename = "Hempstead Branch Customers";
            $color = "#CE8E00";
            break;
        case "LongBeach":
            $linename = "Long Beach Branch Customers";
            $color = "#FF6319";
            break;
        case "Montauk":
            $linename = "Montauk Branch Customers";
            $color = "#006983";
            break;
        case "OysterBay":
            $linename = "Oyster Bay Branch Customers";
            $color = "#00AF3F";
            break;
        case "PortJefferson":
            $linename = "Port Jefferson Branch Customers";
            $color = "#0039A6";
            break;
        case "PortWashington":
            $linename = "Port Washington Branch Customers";
            $color = "#C60C30";
            break;
        case "Ronkonkoma":
            $linename = "Ronkonkoma Branch Customers";
            $color = "#A626AA";
            break;
        case "WestHempstead":
            $linename = "West Hempstead Branch Customers";
            $color = "#00A1DE";
            break;
        // MNR
        case "Hudson":
            $linename = "Hudson Line Customers";
            $color = "#009B3A";
            break;
        case "Harlem":
            $linename = "Harlem Line Customers";
            $color = "#0039A6";
            break;
        case "Wassaic":
            $linename = "Wassaic Line Customers";
            $color = "#0039A6";
            break;                
        case "NewHaven":
            $linename = "New Haven Line Customers";
            $color = "#EE0034";
            break;
        case "NewCanaan":
            $linename = "New Canaan Line Customers";
            $color = "#EE0034";
            break;
        case "Danbury":
            $linename = "Danbury Line Customers";
            $color = "#EE0034";
            break;
        case "Waterbury":
            $linename = "Waterbury Line Customers";
            $color = "#EE0034";
            break;
        case "PascackValley":
            $linename = "Pascack Valley Line Customers";
            $color = "#8E258D";
            break;
        case "PortJervis":
            $linename = "Port Jervis Line Customers";
            $color = "#FF7900";
            break;
    }

    $heading = '<span style="color:' . $color . ';font-size:large;font-weight:bold">' . $linename . '</span><br/>';

    return $heading;
}

/*
 * Implementation of hook_block_view().
 */
function servicestatus_block_view($delta ='') 
{
    $block = array();

    switch ($delta) 
    {
        case 'service-status':
            $block['title'] = t('Service Status');
            $block['subject'] = t('');

            $block['content'] = '<div id="status-whole-block"></div>';
        break;
    }
    
    return $block;
}