<?php
function mta_ssb_init(){
	include 'SSB.inc';

	global $ssb;
	$ssb = new ServiceStatusDataHandler();
}

/**
 * Implements hook_ctools_plugin_api().
 */
function mta_qt_ssb_ctools_plugin_api() {
	list($module, $api) = func_get_args();
	if ($module == "quicktabs" && $api == "quicktabs") {
		return array("version" => "1");
	}
}


function mta_ssb_menu()
{
	$item['gss/%/%'] = array(
			'access arguments' => array('access content'),
			'page callback' => 'mta_ssb_render_service_status',
			'page arguments' => array(1,2),
	);

	$item['service_status_json'] = array(
			'access arguments' => array('access content'),
			'page callback' => 'getSSBAsJson',
	);

	$item['service_status_json.js'] = array(
			'access arguments' => array('access content'),
			'page callback' => 'getSSBAsJson',
	);

	$item['mta/service_status_json.js'] = array(
			'access arguments' => array('access content'),
			'page callback' => 'getSSBAsJson',
	);

	return $item;
}

/*
 * Implementation of hook_block_info().
*/
function mta_ssb_block_info()
{
	$blocks['mta_service_status'] = array(
			'info' => t('MTA Service Status'),
			'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['mta_subway'] = array(
			'info' => t('Subway Service Status'),
			'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['mta_rail'] = array(
			'info' => t('Rail Service Status'),
			'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['mta_bus'] = array(
			'info' => t('Bus Service Status'),
			'cache' => DRUPAL_NO_CACHE,
	);
	$blocks['mta_bnt'] = array(
			'info' => t('Bridge & Tunnel Service Status'),
			'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/*
 * Implementation of hook_block_view().
*/
function mta_ssb_block_view($delta ='')
{
	$block = array();

	global $ssb;

	switch ($delta)
	{
		case 'mta_service_status':
			$block['title'] = t('Service Status');
			$block['subject'] = t('');
			$block['content'] = theme('servicestatus', array());//content' => $ssb->getServiceStatusData(SUBWAY)));//get_ssb('SUBWAY');
			break;
		case 'mta_subway':
			$block['title'] = t('Subway Service Status');
			$block['subject'] = t('');
			$block['content'] = theme('subwayTab', array('content' => $ssb->getServiceStatusData(SUBWAY)));//get_ssb('SUBWAY');
			break;
		case 'mta_rail':
			$block['title'] = t('Rail Service Status');
			$block['subject'] = t('');
			$block['content'] = theme('railTab', array('lirr' => $ssb->getServiceStatusData(LIRR),
			'mnr' => $ssb->getServiceStatusData(MNR)));
			break;
		case 'mta_bus':
		  $block['title'] = t('Bus Service Status');
			$block['subject'] = t('');
			$block['content'] = theme('busTab', array('bus' => $ssb->getServiceStatusData(BUS)));//get_ssb('BUS');
			break;
		case 'mta_bnt':
			$block['title'] = t('Bridge & Tunnel Service Status');
			$block['subject'] = t('');
			$block['content'] = theme('bntTab', array('bnt' => $ssb->getServiceStatusData(BNT)));//get_ssb('BNT');
			break;
	}

	return $block;
}

function mta_ssb_render_service_status($service = '', $col = '')
{
	global $ssb;

	if ($ssb) {
		$html = $ssb->getStatus($service, $col);
		dsm("Before : " . $html);
		$html = html_entity_decode($ssb->getStatus($service, $col));
		dsm("After : " . $html);

		//run $html through MTA input filter to translate tokens to images
		$filteredhtml = check_markup($html, 'full_html');
		//dsm($filteredhtml);
	}

	return $filteredhtml;
}

function getSSBAsJson()
{
	global $ssd;

	$fileContents= file_get_contents("http://www.mta.info/status/serviceStatus.txt");
	$fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
	$fileContents = trim(str_replace('"', "'", $fileContents));

	$simpleXml = simplexml_load_string($fileContents);

	$json = json_encode($simpleXml);

	echo $json;
}

/*
 * Implementation of hook_theme(). Registers the module's own theme implementation.
*/
function mta_ssb_theme(&$existing, $type, $theme, $path)
{
	// Following key is the internal name of the hook.
	return array(
			'servicestatus' => array(
					'variables' => array('content' => NULL),
			),
			'subwayTab' => array (
					'variables' => array('subway' => NULL),
			),
			'railTab' => array (
					'variables' => array('lirr' => NULL, 'mnr' => NULL),
			),
			'busTab' => array (
					'variables' => array('bus' => NULL),
			),
			'bntTab' => array (
					'variables' => array('bnt' => NULL),
			),
	);
}

function mta_ssb_get_rail(){
	global $ssb;
	return theme('railTab', array('lirr' => $ssb->getServiceStatusData(LIRR),
			'mnr' => $ssb->getServiceStatusData(MNR)));
}


/**
 * Implements hook_quicktabs_default_quicktabs().
 * http://drupalcontrib.org/api/drupal/contributions!quicktabs!quicktabs.module/function/quicktabs_build_quicktabs/7
*/
/*
function mta_ssb_quicktabs_default_quicktabs() {
	$export = array();

	$quicktabs = new stdClass();
	$quicktabs->disabled = FALSE
	$quicktabs->api_version = 1;
	$quicktabs->machine_name = 'service_status';
	$quicktabs->ajax = 1;
	$quicktabs->hide_empty_tabs = FALSE;
	$quicktabs->default_tab = 0;
	$quicktabs->title = 'Service Status';
	$quicktabs->tabs = array(
			0 => array(
					'bid' => 'mta_ssb_delta_mta_subway',
					'hide_title' => 1,
					'title' => 'Subway',
					'weight' => '-100',
					'type' => 'block',
			),
			1 => array(
					'bid' => 'mta_ssb_delta_mta_rail',
					'hide_title' => 1,
					'title' => 'Rail',
					'weight' => '-99',
					'type' => 'block',
			),
			2 => array(
					'bid' => 'mta_ssb_delta_mta_bus',
					'hide_title' => 1,
					'title' => 'Bus',
					'weight' => '-98',
					'type' => 'block',
			),
			3 => array(
					'bid' => 'mta_ssb_delta_mta_bnt',
					'hide_title' => 1,
					'title' => 'Bridges & Tunnels',
					'weight' => '-97',
					'type' => 'block',
			),
	);
	$quicktabs->renderer = 'quicktabs';
	$quicktabs->style = 'default';
	$quicktabs->options = array();

	// Translatables
	// Included for use with string extractors like potx.
	t('Bridges & Tunnels');
	t('Bus');
	t('Rail');
	t('Service Status');
	t('Subway');

	$export['service_status'] = $quicktabs;

	return $export;
}
*/

function theme_servicestatus($variables){
	$arrSubway = $variables['content'];

	$rendered = '<div id="statusblock-mta-service-status">';
	$rendered .= '<div class="AsOfTime";">' . mta_ssb_timestamp() . '</div>';
	$mtaquicktabs = array(
			0 => array(
					'bid' => 'mta_ssb_mta_subway',
					'hide_title' => 1,
					'title' => '',
					'weight' => '-100',
					'type' => 'block',
			),
			1 => array(
					'bid' => 'mta_ssb_mta_rail',
					'hide_title' => 1,
					'title' => '',
					'weight' => '-99',
					'type' => 'block',
			),
			2 => array(
					'bid' => 'mta_ssb_mta_bus',
					'hide_title' => 1,
					'title' => '',
					'weight' => '-98',
					'type' => 'block',
			),
			3 => array(
					'bid' => 'mta_ssb_mta_bnt',
					'hide_title' => 1,
					'title' => '',
					'weight' => '-97',
					'type' => 'block',
			),
	);
	$quicktabs_options = array(
			'disabled' => 'FALSE',
	    'api_version' => '1',
			'machine_name' => 'service_status',
			'ajax' => 1,
			'hide_empty_tabs' => 'FALSE',
			'default_tab' => '0',
			'title' => 'Service Status'
			);
	$rendered .= render(quicktabs_build_quicktabs('service_status',$quicktabs_options, $mtaquicktabs));
	//dsm($mtaquicktabs);
	$rendered .= '</div>';

	return $rendered;
}

/*
 * Default theme implementation for rendering Subway Status
*/
function theme_subwayTab($variables)
{
	global $base_url;

	$arrSubway = $variables['content'];

	$rendered = '<div id="subwayDiv" style="float: left; margin-top: 1px;">
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/weekender\'">The Weekender</li>
            <li class="gw list_h" onClick="window.parent.location=\'http://travel.mtanyct.info/serviceadvisory\'">Future Date</li></ul>';

	if (is_array($arrSubway)) {
		for($num=0; $num < count($arrSubway); $num++)
			$rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'mta_ssb') . '/images/img_trans.gif" class="subwayIcon_'.$arrSubway[$num]['name'].'" alt="'.$arrSubway[$num]['name'].' Subway Line Icons"/></div>
                <div style="margin-top: 4px;" class="subwayCategory subway_'.$arrSubway[$num]['status'][0].'">'.$arrSubway[$num]['status'][1].'</div>
                		</div>';
	} else
		$rendered .= '<div class="completeOutage" style="margin: 150px 0 0 0;">' . $arrSubway . '</div>';

	$rendered .= '</div>';

	return $rendered;
}

/*
 * Default theme implementation for rendering LIRR Status
*/
function theme_railTab($variables)
{
	global $base_url;

	$arrLirr = $variables['lirr'];
	$arrMnr = $variables['mnr'];

	// HTML for LIRR
	$rendered = '<div id="railDiv" style="float: left;">
        <span class="RailRoadCompany">Long Island Rail Road</span>
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/lirr/News/PlannedService.htm\'">Future Date</li></ul>';

	// <span class="span-12 railLineItem"><img style="margin-right: 2px;" src="' . $base_url . '/' . drupal_get_path ('module', 'mta_ssb') . '/images/railSquare'.($num+1).'.gif" alt="Rail Icons"/>'.$arrLirr[$num]['name'].'</span>
	//$rendered .= '<span class="span-11 railLineItem"><img style="margin-right: 2px;" src="' . $base_url . '/' . drupal_get_path ('module', 'mta_ssb') . '/images/railSquare'.($num+1).'.gif" alt="Rail Icons"/>'.$arrMnr[$mnum]['name'].'</span>';

	if (is_array($arrLirr)) {
		for($num=0; $num < count($arrLirr); $num++)
			$rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare'. ($num+1) .'"></div>
                <div class="span-11 railLineItem">'. $arrLirr[$num]['name'].'</div>
                		<div class="railStation railCategory '. $arrLirr[$num]['status'][0] .'">'.$arrLirr[$num]['status'][1].'</div>
                		</div>';
	} else
		$rendered .= '<div class="completeOutage" style="margin: 40px 0 150px 0;">' . $arrLirr . '</div>';

				// HTML for MNR
				$rendered .= '<div style="float: left; width: 100%;"><span class="RailRoadCompany">Metro-North Railroad</span>
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/mnr/html/serviceupdates.htm\'">Future Date</li></ul></div>';

						if (is_array($arrMnr)) {
						for($mnum=0; $mnum < count($arrMnr); $mnum++, $num++) {
						$rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">';

								if ($mnum == 2 || $mnum == 4 || $mnum == 5 || $mnum == 6)
									$rendered .= '<div style="margin-left: 20px;" class="span-10 railLineItem">'.$arrMnr[$mnum]['name'].'</div>';
											else
												$rendered .= '<div class="railLineStatus" id="railSquare'. ($num+1) .'"></div>
												<div class="span-11 railLineItem">'. $arrMnr[$mnum]['name'].'</div>';

												$rendered .= '<div class="railStation railCategory '. $arrMnr[$mnum]['status'][0] .'">'.$arrMnr[$mnum]['status'][1].'</div></div>';
						}
    		} else
											$rendered .= '<div class="completeOutage" style="margin: 40px 0 40px 0;">' . $arrMnr . '</div>';

											$rendered .= '</div>';

													return $rendered;
}

/*
* Default theme implementation for rendering Bus Status
 */
function theme_busTab($variables) {
$arrBus = $variables['bus'];

$rendered = '<div id="busDiv" style="float: left; margin-top: 11px;">';

if (is_array($arrBus)) {
for($num=0; $num < count($arrBus); $num++)
	$rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                <span class="span-11 busLineItem">'.$arrBus[$num]['name'].'</span>
                <span class="busCategory '.$arrBus[$num]['status'][0] .'">'.$arrBus[$num]['status'][1].'</span>
                </div>';
        } else
                		$rendered .= '<div class="completeOutage" style="margin: 150px 0 0px 0;">' . $arrBus . '</div>';

                		$rendered .= '</div>';

                		return $rendered;
}

/*
* Default theme implementation for rendering B&T Status
*/
function theme_bntTab($variables) {
$arrBnt = $variables['bnt'];

$rendered = '<div id="bntDiv" style="float: left; margin-top: 12px;">
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/bandt/traffic/advisory.html\'">Future Date</li></ul>';
            // don't end it here   $rendered .='</div>';
            if (is_array($arrBnt)) {
for($num=0; $num < count($arrBnt); $num++)
$rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                <span class="span-12 busLineItem">'.$arrBnt[$num]['name'].'</span>
            		<span class="busCategory '.$arrBnt[$num]['status'][0] .'">'.$arrBnt[$num]['status'][1].'</span>
                		</div>';
} else
$rendered .= '<div class="completeOutage" style="margin: 150px 0 0px 0;">' . $arrBnt . '</div>';

    $rendered .= '</div>';

    return $rendered;
}

function mta_ssb_timestamp() {
		global $ssb;
		return $ssb->getStatusTimeStamp();
}