<?php
/**
 * @file
 * Contains core functions for the File Aliases module.
 */

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
 if (file_exists($file = dirname(__FILE__) . "/modules/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Implements hook_menu().
 */
function file_aliases_menu() {
  $items['filefield_paths/alias/%'] = array(
    'page callback' => 'file_aliases_load_fid',
   'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_file_load().
 */
function file_aliases_file_load($files) {
  foreach ($files as &$file) {
    $filefield_paths_alias = "filefield_paths/alias/{$file->fid}";
    if (($alias = drupal_get_path_alias($filefield_paths_alias)) != $filefield_paths_alias) {
      $file->alias = $alias;
    }
  }
}

/**
 * Implements hook_preprocess_image_style().
 */
function file_aliases_preprocess_image_style(&$variables) {
  $fid = db_query("SELECT fid FROM {file_managed} WHERE uri = :uri", array(':uri' => "{$variables['path']}"))->fetchField();
  $filefield_paths_alias = "filefield_paths/alias/{$fid}";
  if (($alias = drupal_get_path_alias($filefield_paths_alias)) != $filefield_paths_alias) {
    $variables['alias'] = $alias;
  }
}

/**
 * Implements hook_preprocess_image().
 */
function file_aliases_preprocess_image(&$variables) {
  if (isset($variables['style_name']) && isset($variables['alias'])) {
    $variables['path'] = file_create_url($variables['alias']) . '?' . $variables['style_name'];
  }
}

/**
 * Implements hook_file_url_alter().
 *
 * @TODO - Respect 'display alias' checkbox.
 */
function file_aliases_file_url_alter(&$uri) {
  $fid = db_query('SELECT fid FROM {file_managed} WHERE uri = :uri', array(':uri' => $uri))->fetchField();
  if (!empty($fid)) {
    $file = file_load($fid);
    if (isset($file->alias)) $uri = $file->alias;
  }
}

/**
 * Menu callback; File Alias callback.
 */
function file_aliases_load_fid($fid) {
  if (request_uri() == base_path() . "filefield_paths/alias/{$fid}") {
    drupal_not_found();
    exit;
  }

  $results = db_select('file_managed', 'f')
  ->fields('f', array('filemime', 'uri'))
    ->condition('fid', $fid)
    ->execute()
    ->fetchAll();
  $result = current($results);

  // Render Image Style preset if applicable.
  $uri = explode('?', request_uri());
  if (isset($uri[1]) && strpos($result->filemime, 'image') === 0) {
    $image_style = $uri[1];
    $styles = image_styles();
    if (isset($styles[$image_style])) {
      $_GET[IMAGE_DERIVATIVE_TOKEN] = image_style_path_token($image_style, $result->uri);
      $arguments = array_merge(array(image_style_load($image_style), file_uri_scheme($result->uri)), explode('/', str_replace(file_uri_scheme($result->uri) . '://', '', $result->uri)));
      call_user_func_array('image_style_deliver', $arguments);
    }
  }

  if (file_uri_scheme($result->uri) == 'private') {
    $file = explode('://', $result->uri);
    file_download($file[0], $file[1]);
  }

  else {
    header("Content-Type: {$result->filemime}");
    header('Cache-Control: public');
    readfile($result->uri);
  }
}

/**
* Implements hook_file_download().
 */
function file_aliases_file_download($uri) {
  $path = drupal_get_path_alias($_GET['q']);
  $fileinfo = pathinfo($path);
  return array(
    'Cache-Control' => 'public',
    'Content-Disposition' => "filename='{$fileinfo['basename']}'"
  );
}

/**
 * Implements hook_file_delete().
 */
function file_aliases_file_delete($file) {
  $filefield_paths_alias = "filefield_paths/alias/{$file->fid}";
  path_delete(array('source' => $filefield_paths_alias));
}