<?php
function statusblock_init(){
    // include 'ServiceStatus.inc';
    // global $ssd;
    // $ssd = new ServiceStatusDataHandler();
    
    // $options['cache'] = false;
    // $options['preprocess'] = false;
    // $options['type'] = 'file';
    // drupal_add_js('http://newdev.mta-hq.info/service_status_json/'.time()."'", $options);
    // drupal_add_js('http://newdev.mta-hq.info/service_status_json/', $options);
    // drupal_add_js('http://newmta.localhost:8082/service_status_json/', $options);
}
    
/*
 * Implementation of hook_block_info().
 */
function statusblock_block_info() 
{    
    $blocks['mta-service-status'] = array(
            'info' => t('MTA Service Status'),
            'cache' => DRUPAL_NO_CACHE,
     		// 'cache' => DRUPAL_CACHE_GLOBAL,
    );

    return $blocks;
}

/*
 * Implementation of hook_menu
 */
function statusblock_menu()
{
    $item['gss/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'statusblock_render_service_status',
        'page arguments' => array(1,2),
    );

    $item['status/%/%'] = array(
        'title' => "MTA Service Status",
        'access arguments' => array('access content'),
        'page callback' => 'getServiceStatusDetail',
        'page arguments' => array(1,2),
    );

    $item['service_status_json'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'getServiceStatusAsJSON',
        'delivery callback' => 'drupal_json_output',
    );

    return $item;
}

function getServiceStatusDetail($service, $line)
{
    $output = '<div id="status_display"></div>';
    drupal_add_js('jQuery(document).ready(function () { jQuery("#status_display").mtaService("'.$service.'", "'.$line.'"); });', 'inline');
    
    return $output;
}

function getServiceStatusAsJSON()
{
    $fileContents= file_get_contents("http://webqa.mta.info/status/serviceStatus.txt");
    $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
    $fileContents = trim(str_replace('"', "'", $fileContents));
    $simpleXml = simplexml_load_string($fileContents);
    $json = json_encode($simpleXml);
    
    // drupal_json_output($json);
    return $json;
}


function statusblock_render_service_status($service = '', $col = '')
{
    // global $ssd;
    
    // if ($ssd) {
    //     //$html = $ssd->getStatus($service, $col);
    //     //dsm("Before : " . $html);
    //     $html = html_entity_decode($ssd->getStatus($service, $col));
    //     //dsm("After : " . $html);
        
    //     //run $html through MTA input filter to translate tokens to images
    //     $filteredhtml = check_markup($html, 'full_html');
    //     //dsm($filteredhtml);
    // }
    
    return $filteredhtml;
}

/*
 * Implementation of hook_theme(). Registers the module's own theme implementation.
 */
function statusblock_theme(&$existing, $type, $theme, $path)
{    
    // Following key is the internal name of the hook.
    return array(
        'subwayTab' => array (
            'variables' => array('content' => NULL),
        ),
        'railTab' => array (
            'variables' => array('lirr' => NULL, 'mrn' => NULL),
        ),
        'busTab' => array (
            'variables' => array('bus' => NULL),
        ),
        'bntTab' => array (
            'variables' => array('bnt' => NULL),
        ),
    );
}

/*
 * Implementation of hook_block_view().
 */
function statusblock_block_view($delta ='') 
{
    $block = array();

    switch ($delta) 
    {
        case 'mta-service-status':
            $block['title'] = t('Service Status');
            $block['subject'] = t('');

            $subwayHTML = theme('subwayTab', array());
            // $lirrHTML = theme('railTab', array('lirr' => $ssd->getServiceStatusData(LIRR), 
            //     'mnr' => $ssd->getServiceStatusData(MNR)));
            // $busHTML = theme('busTab', array('bus' => $ssd->getServiceStatusData(BUS)));
            $lirrHTML = theme('railTab', array('lirr' => array()));
            $busHTML = theme('busTab', array('bus' => array()));

            // $bntHTML = theme('bntTab', array('bnt' => $ssd->getServiceStatusData(BNT)));
            $bntHTML = theme('bntTab', array('bnt' => array()));
               
            // $block['content'] = '<div id="status-whole-block">'.$subwayHTML.$lirrHTML.$busHTML.$bntHTML.'</div>';
            $block['content'] = '<div id="status-whole-block">'.$subwayHTML.$lirrHTML.$busHTML.$bntHTML.'</div>';
        break;
    }
    
    return $block;
}

// function statusblock_block_view($delta ='') 
// {
//     $block = array();
    
//     global $ssd;

//     switch ($delta) 
//     {
//         case 'mta-service-status':
//             $block['title'] = t('Service Status');
//             $block['subject'] = t('');

//             $subwayHTML = theme('subwayTab', array('content' => $ssd->getServiceStatusData(SUBWAY)));
//             $lirrHTML = theme('railTab', array('lirr' => $ssd->getServiceStatusData(LIRR), 
//                 'mnr' => $ssd->getServiceStatusData(MNR)));
//             $busHTML = theme('busTab', array('bus' => $ssd->getServiceStatusData(BUS)));

//             $bntHTML = theme('bntTab', array('bnt' => $ssd->getServiceStatusData(BNT)));
               
//             $block['content'] = '<div id="status-whole-block">'.$subwayHTML.$lirrHTML.$busHTML.$bntHTML.'</div>';
//         break;
//     }
    
//     return $block;
// }

/*
 * Default theme implementation for rendering Subway Status
 */
function theme_subwayTab($variables)
{
    global $base_url;
    
    // $arrSubway = $variables['content'];
    
    $rendered = '<div id="subwayDiv" style="float: left; margin-top: 1px;">
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/weekender\'">The Weekender</li>
            <li class="gw list_h" onClick="window.parent.location=\'http://travel.mtanyct.info/serviceadvisory\'">Future Date</li></ul>';
    
    // if (is_array($arrSubway)) {
    //     for($num=0; $num < count($arrSubway); $num++)     
    //         $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
    //             <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_'.$arrSubway[$num]['name'].'" alt="'.$arrSubway[$num]['name'].' Subway Line Icons"/></div>
    //             <div style="margin-top: 4px;" id="'.$arrSubway[$num]['name'].'" class="subwayCategory"></div>
    //         </div>';
    // } else
    //     $rendered .= '<div class="completeOutage" style="margin: 150px 0 0 0;">' . $arrSubway . '</div>';

    $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_123" alt="123 Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="123" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_456" alt="456 Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="456" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_7" alt="7 Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="7" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_ACE" alt="ACE Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="ACE" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_BDFM" alt="BDFM Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="BDFM" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_G" alt="G Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="G" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_JZ" alt="JZ Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="JZ" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_L" alt="L Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="L" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_NQR" alt="L Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="NQR" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_S" alt="L Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="S" class="subwayCategory"></div>
                </div>

                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 4px 0;">
                    <div class="span-11"><img width="1" height="1" src="' . $base_url . '/' . drupal_get_path('module', 'statusblock') . '/images/img_trans.gif" class="subwayIcon_SIR" alt="L Subway Line Icons"/></div>
                    <div style="margin-top: 4px;" id="SIR" class="subwayCategory"></div>
                </div>
                ';    
    
    $rendered .= '</div>';

    return $rendered;
}

/*
 * Default theme implementation for rendering LIRR Status
 */
function theme_railTab($variables)
{
    global $base_url;
    
    // $arrLirr = $variables['lirr'];
    // $arrMnr = $variables['mnr'];

    // HTML for LIRR
    $rendered = '<div id="railDiv" style="float: left; display: none;">
        <span class="RailRoadCompany">Long Island Rail Road</span>
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/lirr/News/PlannedService.htm\'">Future Date</li></ul>';

    $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare1"></div>
                <div class="span-11 railLineItem">City Terminal Zone</div>
                <div id="CityTerminalZone" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare2"></div>
                <div class="span-11 railLineItem">Babylon</div>
                <div id="Babylon" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare3"></div>
                <div class="span-11 railLineItem">Far Rockaway</div>
                <div id="FarRockaway" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare4"></div>
                <div class="span-11 railLineItem">Hempstead</div>
                <div id="Hempstead" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare5"></div>
                <div class="span-11 railLineItem">Long Beach</div>
                <div id="LongBeach" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare6"></div>
                <div class="span-11 railLineItem">Montauk</div>
                <div id="Montauk" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare7"></div>
                <div class="span-11 railLineItem">Oyster Bay</div>
                <div id="OysterBay" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare8"></div>
                <div class="span-11 railLineItem">Port Jefferson</div>
                <div id="PortJefferson" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare9"></div>
                <div class="span-11 railLineItem">Port Washington</div>
                <div id="PortWashington" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare10"></div>
                <div class="span-11 railLineItem">Ronkonkoma</div>
                <div id="Ronkonkoma" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare11"></div>
                <div class="span-11 railLineItem">West Hempstead</div>
                <div id="WestHempstead" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 100%;"><span class="RailRoadCompany">Metro-North Railroad</span>
                <ul style="float: right; padding:0; margin:0">
                    <li class="gw list_h" onClick="window.parent.location="http://mta.info/mnr/html/serviceupdates.htm">Future Date</li>
                </ul>
            </div>


            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare12"></div>
                <div class="span-11 railLineItem">Hudson</div>
                <div id="Hudson" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare13"></div>
                <div class="span-11 railLineItem">Harlem</div>
                <div id="Harlem" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus"></div>
                <div style="margin-left: 10px;" class="span-10 railLineItem">Wassaic</div>
                <div id="Wassaic" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare15"></div>
                <div class="span-11 railLineItem">New Haven</div>
                <div id="NewHaven" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus"></div>
                <div style="margin-left: 10px;" class="span-10 railLineItem">New Canaan</div>
                <div id="NewCanaan" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus"></div>
                <div style="margin-left: 10px;" class="span-10 railLineItem">Danbury</div>
                <div id="Danbury" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus"></div>
                <div style="margin-left: 10px;" class="span-10 railLineItem">Waterbury</div>
                <div id="Waterbury" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare19"></div>
                <div class="span-11 railLineItem">Pascack Valley</div>
                <div id="PascackValley" class="railStation railCategory"></div>
            </div>
            <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
                <div class="railLineStatus" id="railSquare20"></div>
                <div class="span-11 railLineItem">Port Jervis</div>
                <div id="PortJervis" class="railStation railCategory"></div>
            </div>
                ';

    // if (is_array($arrLirr)) {  
    //     for($num=0; $num < count($arrLirr); $num++)     
    //         $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">
    //             <div class="railLineStatus" id="railSquare'. ($num+1) .'"></div>
    //             <div class="span-11 railLineItem">'. $arrLirr[$num]['name'].'</div>
    //             <div class="railStation railCategory '. $arrLirr[$num]['status'][0] .'">'.$arrLirr[$num]['status'][1].'</div>
    //         </div>';
    // } else
    //     $rendered .= '<div class="completeOutage" style="margin: 40px 0 150px 0;">' . $arrLirr . '</div>';
    
    // // HTML for MNR
    // $rendered .= '<div style="float: left; width: 100%;"><span class="RailRoadCompany">Metro-North Railroad</span>
    //     <ul style="float: right; padding:0; margin:0">
    //         <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/mnr/html/serviceupdates.htm\'">Future Date</li></ul></div>';
    
    // if (is_array($arrMnr)) {
    //     for($mnum=0; $mnum < count($arrMnr); $mnum++, $num++) {  
    //         $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 1px 0;">';

    //         if ($mnum == 2 || $mnum == 4 || $mnum == 5 || $mnum == 6)
    //             $rendered .= '<div style="margin-left: 20px;" class="span-10 railLineItem">'.$arrMnr[$mnum]['name'].'</div>';
    //         else
    //             $rendered .= '<div class="railLineStatus" id="railSquare'. ($num+1) .'"></div>
    //                 <div class="span-11 railLineItem">'. $arrMnr[$mnum]['name'].'</div>';
            
    //         $rendered .= '<div class="railStation railCategory '. $arrMnr[$mnum]['status'][0] .'">'.$arrMnr[$mnum]['status'][1].'</div></div>';
    //     }
    // } else
    //     $rendered .= '<div class="completeOutage" style="margin: 40px 0 40px 0;">' . $arrMnr . '</div>';
    
    $rendered .= '</div>';

    return $rendered;
}

/*
 * Default theme implementation for rendering Bus Status
 */
function theme_busTab($variables) {
    // $arrBus = $variables['bus'];
    
    $rendered = '<div id="busDiv" style="float: left; display: none; margin-top: 11px;">';

    $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">B1 - B83</span>
                    <span id="B1-B83" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">B100 - B103</span>
                    <span id="B100-B103" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">BM1 - BM5</span>
                    <span id="BM1-BM5" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">BX1 - BX55</span>
                    <span id="BX1-BX55" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">BXM1 - BXM18</span>
                    <span id="BXM1-BXM18" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">M1 - M116</span>
                    <span id="M1-M116" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">Q1 - Q113</span>
                    <span id="Q1-Q113" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">QM1 - QM25</span>
                    <span id="QM1-QM25" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">S40 - S98</span>
                    <span id="S40-S98" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
                    <span class="span-11 busLineItem">x1 - x68</span>
                    <span id="x1-x68" class="busCategory"></span>
                </div>';
    
    // if (is_array($arrBus)) {
    //     for($num=0; $num < count($arrBus); $num++)     
    //         $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 9px 0;">
    //             <span class="span-11 busLineItem">'.$arrBus[$num]['name'].'</span>
    //             <span class="busCategory '.$arrBus[$num]['status'][0] .'">'.$arrBus[$num]['status'][1].'</span>
    //         </div>';
    // } else
    //     $rendered .= '<div class="completeOutage" style="margin: 150px 0 0px 0;">' . $arrBus . '</div>'; 
    
    $rendered .= '</div>';

    return $rendered;
}

/*
 * Default theme implementation for rendering B&T Status
 */
function theme_bntTab($variables) {
    // $arrBnt = $variables['bnt'];
    
    $rendered = '<div id="bntDiv" style="float: left; display: none; margin-top: 12px;">
        <ul style="float: right; padding:0; margin:0">
            <li class="gw list_h" onClick="window.parent.location=\'http://mta.info/bandt/traffic/advisory.html\'">Future Date</li></ul>';

    $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Throgs Neck</span>
                    <span id="ThrogsNeck" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Henry Hudson</span>
                    <span id="HenryHudson" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Marine Parkway</span>
                    <span id="MarineParkway" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Bronx-Whitestone</span>
                    <span id="Bronx-Whitestone" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Hugh L. Carey</span>
                    <span id="HughLCarey" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Queens Midtown</span>
                    <span id="QueensMidtown" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Robert F. Kennedy</span>
                    <span id="RobertFKennedy" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Cross Bay</span>
                    <span id="CrossBay" class="busCategory"></span>
                </div>
                <div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
                    <span class="span-12 busLineItem">Verrazano-Narrows</span>
                    <span id="Verrazano-Narrows" class="busCategory"></span>
                </div>';

    // if (is_array($arrBnt)) {
    //     for($num=0; $num < count($arrBnt); $num++)     
    //         $rendered .= '<div style="float: left; width: 220px; border-bottom: 1px solid #7B7B98; padding: 10px 0;">
    //             <span class="span-12 busLineItem">'.$arrBnt[$num]['name'].'</span>
    //             <span class="busCategory '.$arrBnt[$num]['status'][0] .'">'.$arrBnt[$num]['status'][1].'</span>
    //         </div>';
    // } else
    //     $rendered .= '<div class="completeOutage" style="margin: 150px 0 0px 0;">' . $arrBnt . '</div>';
    
    $rendered .= '</div>';

    return $rendered;
}

// function statusblock_preprocess_block(&$variables) {
//     if ($variables['block']->delta === 'mta-service-status') {
//         global $ssd;
//         $variables['timestamp'] = $ssd->getStatusTimeStamp();
//     }  
// }