<?php

/**
 * @defgroup mta_header
 *
 * Author:  Wes Roepken aka lipcpro < wes at lipcpro dot com >
 * Date:    06/25/2013
 *
 * @file mta_header.module
 *
 *
 * @ingroup mta_header
 */

function mta_header_init() {
  drupal_add_library('system', 'drupal.ajax');
}

function mta_header_menu() {
  $items['mta/header'] = array(
      'title' => 'MTA Header',
      'page callback' => 'theme_mta_header_header',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implements hook_block_info()
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function mta_header_block_info()
{
  $blocks = array();
  $blocks['mta_header_header'] = array('info' => t('mta header block'));
  return $blocks;
}

/**
 * Implements hook_block_view()
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function mta_header_block_view($delta = '')
{
  $block = array();
  switch ($delta) {
    case 'mta_header_header':
      $block['subject'] = NULL;
      $block['content'] = theme_mta_header_header();
      break;
    default:
      $block = array();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function mta_header_theme()
{
  return array(
    'mta_header_header' => array(
      'render_element' => 'block',
    ),
  );
}//*/

function theme_mta_header_header() {
  $base = $_SERVER['HTTP_HOST'];
  $output = '<div id="topbar">
                                <div id="branding">
                                        <a href="http://www.mta.info"><img src="http://';
        $output .= $base;
        $output .= '/sites/all/themes/mta/images/mta_info.gif" alt="Metropolitan Transportation Authority logo"></a>
                                </div> <!-- branding -->
                                <div id="middle-header">';
        $block = block_load('menu', 'menu-topbar-links');
        $output2 = _block_get_renderable_array(_block_render_blocks(array($block)));
        $output .= drupal_render($output2);
        $output .= '
            </div> <!-- middle-header -->
               <div id="search">
                  <div class="region region-header-right">';
        $block = block_load('google_appliance', 'ga_block_search_form');
        $output2 = _block_get_renderable_array(_block_render_blocks(array($block)));
        $output .= drupal_render($output2);
        //$mta_block = drupal_get_form('ga_block_search_form');
        //$output .= render($mta_block);
  $output .= '
        </div><!-- region-header-right -->
      </div><!-- search -->
                         </div><!-- topbar -->
                        <div id="navbar">';
  $block = block_load('superfish', 1);
  $output2 = _block_get_renderable_array(_block_render_blocks(array($block)));
  $output .= drupal_render($output2);
  //$mta_block = module_invoke('superfish', 'block', 'view', '1');
  //$output .= render($mta_block['content']);
  //$output .=  render($page['navbar']);
  $output .= '
      </div><!-- navbar -->';
  print render($output);
  exit;
}
